apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: okteto/frontend:latest
        name: frontend
        
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP  
  ports:
  - name: frontend
    port: 8000
  selector:
    app: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: okteto
      containers:
      - image: okteto/api:latest
        name: api
        
---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP  
  ports:
  - name: api
    port: 8000
  selector:
    app: api

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: okteto
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: cloud.okteto.net
    http:
      paths:
      - path: /api
        backend: 
          serviceName: okteto-api
          servicePort: 8000
      - path: /
        backend:
          serviceName: okteto-frontend
          servicePort: 8000
  tls:
  - hosts:
    - cloud.okteto.net
    secretName: okteto