apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-frontend"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.frontend.port }}
              protocol: TCP
          env:
            - name: GITHUB_CLIENTID
              value: {{ .Values.githubAuth.clientId }}
          livenessProbe:
            httpGet:
              path: /index.html
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /index.html
              port: {{ .Values.services.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          
          resources:
{{ toYaml .Values.resources.frontend | indent 12 }}