{{- if .Values.ingress.enabled -}}
{{- $fullName := include "okteto.fullname" . -}}
{{- $root := . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "okteto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "okteto.name" . }}
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: "/github"
            backend:
              serviceName: api
              servicePort: {{ $root.Values.services.api.port }}
          - path: "/graphql"
            backend:
              serviceName: api
              servicePort: {{ $root.Values.services.api.port }}
          - path: "/"
            backend:
              serviceName: frontend
              servicePort: {{ $root.Values.services.frontend.port }}
          
  {{- end }}
{{- end }}
