{{ if .Values.rbac.install }}
{{- $serviceName := include "okteto.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ .Values.rbac.roleBindingKind }}
metadata:
  name: {{ $serviceName }}-role-binding
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.roleKind }}
  name: {{ .Values.rbac.roleRef }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{ end }}