apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okteto.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-secret"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  githubClientId: {{ required "A valid .Values.githubAuth.clientId is required" .Values.githubAuth.clientId | b64enc | quote }}
  githubClientSecret: {{ required "A valid .Values.githubAuth.clientSecret is required" .Values.githubAuth.clientSecret | b64enc | quote }}
  mgApiKey: {{ .Values.mailgun.apiKey | b64enc | quote }}
  
