# Default values for okteto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# In order to use github authentication you need to create an OAuth App and set the client and secret here
githubAuth:
  clientId: ""
  clientSecret: ""

replicas: 2

images:
  api:
    repository: gcr.io/okteto-prod/api
    tag: 0.1.0
  frontend:
    repository: gcr.io/okteto-prod/frontend
    tag: 0.1.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

clusterPublicEndpoint: ""
oktetoBaseDomain: ""
oktetoClusterCIDR: ""

services:
  type: ClusterIP
  api:
    port: 8000
  frontend:
    port: 8000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Install Default RBAC roles and bindings
rbac:
  install: false
  # Role reference
  roleRef: cluster-admin
  # Role kind (Role or ClusterRole)
  roleKind: ClusterRole
  # Role binding kind (RoleBinding or ClusterRoleBinding)
  roleBindingKind: ClusterRoleBinding

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi