apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.crd.okteto.com
  labels:
    app.kubernetes.io/name: users.crd.okteto.com
spec:
  group: crd.okteto.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
