apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: {{ include "okteto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "okteto.name" . }}
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "okteto.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "okteto.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-api"
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
{{ toYaml .Values.resources.api | indent 12 }}
        - name: "{{ .Chart.Name }}-frontend"
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
{{ toYaml .Values.resources.frontend | indent 12 }}
        - name: inotify
          image: busybox:latest
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - "echo 10048576 > /proc-aux/sys/fs/inotify/max_user_watches && tail -f /dev/null"
          volumeMounts:
          - mountPath: /proc-aux
            name: proc-volume
      volumes:
      - name: proc-volume
        hostPath:
          path: /proc